
services:
  react-project:
    container_name: react-project
    image: react-project-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/react-project
      - /react-project/node_modules
    command: npm run dev

